import {AppRouterCacheProvider} from "@mui/material-nextjs/v14-appRouter";
import {Inter} from "next/font/google";
import Providers from "@/components/providers";
import {ReactNode} from "react";
import {API_BASE} from "@/consts/global";
import {CategoryComposite, MenuItem} from "@/consts/types";
import CategorySidebar from "@/components/menu/categorySidebar";
import Toolbar from "@/components/menu/toolbar";
import styles from '../styles/layout.module.scss';
import MenuDrawer from "@/components/menu/menuDrawer";

const inter = Inter({   weight: '400',
    subsets: ['latin'],
    display: 'swap', })

async function getCategories() {
    const url: string = API_BASE + "/item-category/tree"
    const categories: CategoryComposite[] | undefined = await fetch(API_BASE + "/item-category/tree", {
        method: "GET"
    }).then(data => data.json())
        .then((categories: CategoryComposite[]) => {
            return categories
        })
        .catch(error => {
        console.log("error" + error + API_BASE)
        return undefined
    })


    return categories
}
async function getMenuList() {
    const menuList: MenuItem[] | undefined = await fetch(API_BASE + "/menu/", {
        method: "GET",
        cache: "no-cache"
    }).then(data => data.json())
        .then((menuItems: MenuItem[]) => {
            return menuItems
        })
        .catch(error => {
            console.log("error" + error + API_BASE)
            return undefined
        })


    return menuList


}

export default async function RootLayout({
                                       children,
                                   }: {
    children: ReactNode
}) {
    //TODO OSTALO OD SIDEBAR, PREMJESTI KADA NAPRAVIS PAGE
    // const initialCategories = await getCategories()


    const menuListParam = await getMenuList()

    return (
        <AppRouterCacheProvider>
            <html lang="en" className={inter.className}>
            <body>
            <title>WebShop</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={""}/>
            <link href="https://fonts.googleapis.com/css2?family=Fuzzy+Bubbles:wght@400;700&family=Roboto:ital,wght@0,100;0,200;0,300;0,800;1,200&family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
                  rel="stylesheet"/>
            <Providers>
                <div className={styles.layout}>
                    <Toolbar className={styles.toolbar} menuListParam={menuListParam ??  []} />
                    <div className={styles.contentContainer}>
                        {
                        }
                        {//MAKNUTO NA PAGE SA SAMIM PROIZVODIMA
                            /*<CategorySidebar className={styles.sidebar} initialCategories={initialCategories != undefined ? initialCategories : []}/>*/}
                        <main className={styles.content}>
                            {children}
                        </main>
                        { }
                    </div>
                </div>
            </Providers>
            </body>
            </html>
        </AppRouterCacheProvider>
    )
}